// Mocks generated by Mockito 5.4.5 from annotations
// in gimelstudio/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:ui' as _i5;

import 'package:flutter/material.dart' as _i6;
import 'package:flutter/services.dart' as _i26;
import 'package:gimelstudio/models/canvas_item.dart' as _i14;
import 'package:gimelstudio/models/document.dart' as _i20;
import 'package:gimelstudio/models/layer.dart' as _i3;
import 'package:gimelstudio/models/node_base.dart' as _i4;
import 'package:gimelstudio/models/node_property.dart' as _i16;
import 'package:gimelstudio/models/photo.dart' as _i34;
import 'package:gimelstudio/models/tool.dart' as _i2;
import 'package:gimelstudio/services/canvas_service.dart' as _i32;
import 'package:gimelstudio/services/cursor_tool_service.dart' as _i25;
import 'package:gimelstudio/services/document_service.dart' as _i19;
import 'package:gimelstudio/services/evaluation_service.dart' as _i21;
import 'package:gimelstudio/services/export_service.dart' as _i22;
import 'package:gimelstudio/services/file_service.dart' as _i11;
import 'package:gimelstudio/services/hand_tool_service.dart' as _i31;
import 'package:gimelstudio/services/id_service.dart' as _i17;
import 'package:gimelstudio/services/image_service.dart' as _i12;
import 'package:gimelstudio/services/image_tool_service.dart' as _i33;
import 'package:gimelstudio/services/layers_service.dart' as _i13;
import 'package:gimelstudio/services/node_registry_service.dart' as _i18;
import 'package:gimelstudio/services/nodegraphs_service.dart' as _i15;
import 'package:gimelstudio/services/overlays_service.dart' as _i29;
import 'package:gimelstudio/services/rectangle_tool_service.dart' as _i27;
import 'package:gimelstudio/services/text_tool_service.dart' as _i35;
import 'package:gimelstudio/services/tool_service.dart' as _i28;
import 'package:gimelstudio/services/viewport_service.dart' as _i10;
import 'package:gimelstudio/ui/common/enums.dart' as _i23;
import 'package:gimelstudio/ui/widgets/viewport_panel/viewport_panel.dart' as _i30;
import 'package:image/image.dart' as _i24;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:stacked_services/stacked_services.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeToolModeEventHandler_0 extends _i1.SmartFake implements _i2.ToolModeEventHandler {
  _FakeToolModeEventHandler_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLayer_1 extends _i1.SmartFake implements _i3.Layer {
  _FakeLayer_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNode_2 extends _i1.SmartFake implements _i4.Node {
  _FakeNode_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeImage_3 extends _i1.SmartFake implements _i5.Image {
  _FakeImage_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRect_4 extends _i1.SmartFake implements _i5.Rect {
  _FakeRect_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMouseCursor_5 extends _i1.SmartFake implements _i6.MouseCursor {
  _FakeMouseCursor_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i6.DiagnosticLevel? minLevel = _i6.DiagnosticLevel.info}) => super.toString();
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i7.NavigationService {
  @override
  String get previousRoute => (super.noSuchMethod(
        Invocation.getter(#previousRoute),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#previousRoute),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#previousRoute),
        ),
      ) as String);

  @override
  String get currentRoute => (super.noSuchMethod(
        Invocation.getter(#currentRoute),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#currentRoute),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#currentRoute),
        ),
      ) as String);

  @override
  _i6.GlobalKey<_i6.NavigatorState>? nestedNavigationKey(int? index) => (super.noSuchMethod(
        Invocation.method(
          #nestedNavigationKey,
          [index],
        ),
        returnValueForMissingStub: null,
      ) as _i6.GlobalKey<_i6.NavigatorState>?);

  @override
  void config({
    bool? enableLog,
    bool? defaultPopGesture,
    bool? defaultOpaqueRoute,
    Duration? defaultDurationTransition,
    bool? defaultGlobalState,
    _i7.Transition? defaultTransitionStyle,
    String? defaultTransition,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #config,
          [],
          {
            #enableLog: enableLog,
            #defaultPopGesture: defaultPopGesture,
            #defaultOpaqueRoute: defaultOpaqueRoute,
            #defaultDurationTransition: defaultDurationTransition,
            #defaultGlobalState: defaultGlobalState,
            #defaultTransitionStyle: defaultTransitionStyle,
            #defaultTransition: defaultTransition,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<T?>? navigateWithTransition<T>(
    _i6.Widget? page, {
    bool? opaque,
    String? transition = '',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i6.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i7.Transition? transitionClass,
    _i7.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i9.Future<T?>?);

  @override
  _i9.Future<T?>? replaceWithTransition<T>(
    _i6.Widget? page, {
    bool? opaque,
    String? transition = '',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i6.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i7.Transition? transitionClass,
    _i7.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i9.Future<T?>?);

  @override
  bool back<T>({
    dynamic result,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #back,
          [],
          {
            #result: result,
            #id: id,
          },
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void popUntil(
    _i6.RoutePredicate? predicate, {
    int? id,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #popUntil,
          [predicate],
          {#id: id},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void popRepeated(int? popTimes) => super.noSuchMethod(
        Invocation.method(
          #popRepeated,
          [popTimes],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<T?>? navigateTo<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i6.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateTo,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i9.Future<T?>?);

  @override
  _i9.Future<T?>? navigateToView<T>(
    _i6.Widget? view, {
    dynamic arguments,
    int? id,
    bool? opaque,
    _i6.Curve? curve,
    Duration? duration,
    bool? fullscreenDialog = false,
    bool? popGesture,
    bool? preventDuplicates = true,
    _i7.Transition? transition,
    _i7.Transition? transitionStyle,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateToView,
          [view],
          {
            #arguments: arguments,
            #id: id,
            #opaque: opaque,
            #curve: curve,
            #duration: duration,
            #fullscreenDialog: fullscreenDialog,
            #popGesture: popGesture,
            #preventDuplicates: preventDuplicates,
            #transition: transition,
            #transitionStyle: transitionStyle,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i9.Future<T?>?);

  @override
  _i9.Future<T?>? replaceWith<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i6.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWith,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i9.Future<T?>?);

  @override
  _i9.Future<T?>? clearStackAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i9.Future<T?>?);

  @override
  _i9.Future<T?>? clearStackAndShowView<T>(
    _i6.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i9.Future<T?>?);

  @override
  _i9.Future<T?>? clearTillFirstAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i9.Future<T?>?);

  @override
  _i9.Future<T?>? clearTillFirstAndShowView<T>(
    _i6.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i9.Future<T?>?);

  @override
  _i9.Future<T?>? pushNamedAndRemoveUntil<T>(
    String? routeName, {
    _i6.RoutePredicate? predicate,
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNamedAndRemoveUntil,
          [routeName],
          {
            #predicate: predicate,
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i9.Future<T?>?);
}

/// A class which mocks [BottomSheetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBottomSheetService extends _i1.Mock implements _i7.BottomSheetService {
  @override
  void setCustomSheetBuilders(Map<dynamic, _i7.SheetBuilder>? builders) => super.noSuchMethod(
        Invocation.method(
          #setCustomSheetBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<_i7.SheetResponse<dynamic>?> showBottomSheet({
    required String? title,
    String? description,
    String? confirmButtonTitle = 'Ok',
    String? cancelButtonTitle,
    bool? enableDrag = true,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
    double? elevation = 1.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showBottomSheet,
          [],
          {
            #title: title,
            #description: description,
            #confirmButtonTitle: confirmButtonTitle,
            #cancelButtonTitle: cancelButtonTitle,
            #enableDrag: enableDrag,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
            #elevation: elevation,
          },
        ),
        returnValue: _i9.Future<_i7.SheetResponse<dynamic>?>.value(),
        returnValueForMissingStub: _i9.Future<_i7.SheetResponse<dynamic>?>.value(),
      ) as _i9.Future<_i7.SheetResponse<dynamic>?>);

  @override
  _i9.Future<_i7.SheetResponse<T>?> showCustomSheet<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i5.Color? barrierColor = const _i5.Color(2315255808),
    double? elevation = 1.0,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    String? barrierLabel = '',
    dynamic customData,
    R? data,
    bool? enableDrag = true,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomSheet,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #elevation: elevation,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #barrierLabel: barrierLabel,
            #customData: customData,
            #data: data,
            #enableDrag: enableDrag,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
          },
        ),
        returnValue: _i9.Future<_i7.SheetResponse<T>?>.value(),
        returnValueForMissingStub: _i9.Future<_i7.SheetResponse<T>?>.value(),
      ) as _i9.Future<_i7.SheetResponse<T>?>);

  @override
  void completeSheet(_i7.SheetResponse<dynamic>? response) => super.noSuchMethod(
        Invocation.method(
          #completeSheet,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogService extends _i1.Mock implements _i7.DialogService {
  @override
  void registerCustomDialogBuilders(Map<dynamic, _i7.DialogBuilder>? builders) => super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerCustomDialogBuilder({
    required dynamic variant,
    required _i6.Widget Function(
      _i6.BuildContext,
      _i7.DialogRequest<dynamic>,
      dynamic Function(_i7.DialogResponse<dynamic>),
    )? builder,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilder,
          [],
          {
            #variant: variant,
            #builder: builder,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<_i7.DialogResponse<dynamic>?> showDialog({
    String? title,
    String? description,
    String? cancelTitle,
    _i5.Color? cancelTitleColor,
    String? buttonTitle = 'Ok',
    _i5.Color? buttonTitleColor,
    bool? barrierDismissible = false,
    _i6.RouteSettings? routeSettings,
    _i6.GlobalKey<_i6.NavigatorState>? navigatorKey,
    _i7.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #buttonTitle: buttonTitle,
            #buttonTitleColor: buttonTitleColor,
            #barrierDismissible: barrierDismissible,
            #routeSettings: routeSettings,
            #navigatorKey: navigatorKey,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i9.Future<_i7.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub: _i9.Future<_i7.DialogResponse<dynamic>?>.value(),
      ) as _i9.Future<_i7.DialogResponse<dynamic>?>);

  @override
  _i9.Future<_i7.DialogResponse<T>?> showCustomDialog<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i5.Color? barrierColor = const _i5.Color(2315255808),
    bool? barrierDismissible = false,
    String? barrierLabel = '',
    bool? useSafeArea = true,
    _i6.RouteSettings? routeSettings,
    _i6.GlobalKey<_i6.NavigatorState>? navigatorKey,
    _i6.RouteTransitionsBuilder? transitionBuilder,
    dynamic customData,
    R? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomDialog,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #barrierDismissible: barrierDismissible,
            #barrierLabel: barrierLabel,
            #useSafeArea: useSafeArea,
            #routeSettings: routeSettings,
            #navigatorKey: navigatorKey,
            #transitionBuilder: transitionBuilder,
            #customData: customData,
            #data: data,
          },
        ),
        returnValue: _i9.Future<_i7.DialogResponse<T>?>.value(),
        returnValueForMissingStub: _i9.Future<_i7.DialogResponse<T>?>.value(),
      ) as _i9.Future<_i7.DialogResponse<T>?>);

  @override
  _i9.Future<_i7.DialogResponse<dynamic>?> showConfirmationDialog({
    String? title,
    String? description,
    String? cancelTitle = 'Cancel',
    _i5.Color? cancelTitleColor,
    String? confirmationTitle = 'Ok',
    _i5.Color? confirmationTitleColor,
    bool? barrierDismissible = false,
    _i6.RouteSettings? routeSettings,
    _i7.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showConfirmationDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #confirmationTitle: confirmationTitle,
            #confirmationTitleColor: confirmationTitleColor,
            #barrierDismissible: barrierDismissible,
            #routeSettings: routeSettings,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i9.Future<_i7.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub: _i9.Future<_i7.DialogResponse<dynamic>?>.value(),
      ) as _i9.Future<_i7.DialogResponse<dynamic>?>);

  @override
  void completeDialog(_i7.DialogResponse<dynamic>? response) => super.noSuchMethod(
        Invocation.method(
          #completeDialog,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ViewportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockViewportService extends _i1.Mock implements _i10.ViewportService {
  @override
  _i2.Tool get activeTool => (super.noSuchMethod(
        Invocation.getter(#activeTool),
        returnValue: _i2.Tool.cursor,
        returnValueForMissingStub: _i2.Tool.cursor,
      ) as _i2.Tool);

  @override
  _i2.ToolModeEventHandler get toolModeHandler => (super.noSuchMethod(
        Invocation.getter(#toolModeHandler),
        returnValue: _FakeToolModeEventHandler_0(
          this,
          Invocation.getter(#toolModeHandler),
        ),
        returnValueForMissingStub: _FakeToolModeEventHandler_0(
          this,
          Invocation.getter(#toolModeHandler),
        ),
      ) as _i2.ToolModeEventHandler);

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  void setActiveTool(_i2.Tool? tool) => super.noSuchMethod(
        Invocation.method(
          #setActiveTool,
          [tool],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) => super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileService extends _i1.Mock implements _i11.FileService {
  @override
  _i9.Future<String?> getSaveFilePath({dynamic suggestedName = 'untitled'}) => (super.noSuchMethod(
        Invocation.method(
          #getSaveFilePath,
          [],
          {#suggestedName: suggestedName},
        ),
        returnValue: _i9.Future<String?>.value(),
        returnValueForMissingStub: _i9.Future<String?>.value(),
      ) as _i9.Future<String?>);

  @override
  _i9.Future<void> saveFile(String? content) => (super.noSuchMethod(
        Invocation.method(
          #saveFile,
          [content],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [ImageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageService extends _i1.Mock implements _i12.ImageService {
  @override
  String get imagePath => (super.noSuchMethod(
        Invocation.getter(#imagePath),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#imagePath),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#imagePath),
        ),
      ) as String);

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  void setImagePath(String? path) => super.noSuchMethod(
        Invocation.method(
          #setImagePath,
          [path],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) => super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LayersService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLayersService extends _i1.Mock implements _i13.LayersService {
  @override
  List<_i3.Layer> get selectedLayers => (super.noSuchMethod(
        Invocation.getter(#selectedLayers),
        returnValue: <_i3.Layer>[],
        returnValueForMissingStub: <_i3.Layer>[],
      ) as List<_i3.Layer>);

  @override
  List<_i3.Layer> get layers => (super.noSuchMethod(
        Invocation.getter(#layers),
        returnValue: <_i3.Layer>[],
        returnValueForMissingStub: <_i3.Layer>[],
      ) as List<_i3.Layer>);

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  void setLayerSelected(_i3.Layer? selectedLayer) => super.noSuchMethod(
        Invocation.method(
          #setLayerSelected,
          [selectedLayer],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addLayerToSelected(_i3.Layer? layer) => super.noSuchMethod(
        Invocation.method(
          #addLayerToSelected,
          [layer],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeFromSelected(_i3.Layer? layer) => super.noSuchMethod(
        Invocation.method(
          #removeFromSelected,
          [layer],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deselectAllLayers() => super.noSuchMethod(
        Invocation.method(
          #deselectAllLayers,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLayerBlendMode(
    _i3.Layer? layer,
    String? blendMode,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setLayerBlendMode,
          [
            layer,
            blendMode,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLayerOpacity(
    _i3.Layer? layer,
    int? opacity,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setLayerOpacity,
          [
            layer,
            opacity,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLayerVisibility(
    _i3.Layer? layer,
    bool? isVisible,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setLayerVisibility,
          [
            layer,
            isVisible,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLayerLocked(
    _i3.Layer? layer,
    bool? isLocked,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setLayerLocked,
          [
            layer,
            isLocked,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reorderLayers(
    int? oldIndex,
    int? newIndex,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #reorderLayers,
          [
            oldIndex,
            newIndex,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, _i4.Node> newDefaultNodes(
    String? type,
    String? outputLabel,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #newDefaultNodes,
          [
            type,
            outputLabel,
          ],
        ),
        returnValue: <String, _i4.Node>{},
        returnValueForMissingStub: <String, _i4.Node>{},
      ) as Map<String, _i4.Node>);

  @override
  _i3.Layer addNewLayer({String? type = 'rectangle'}) => (super.noSuchMethod(
        Invocation.method(
          #addNewLayer,
          [],
          {#type: type},
        ),
        returnValue: _FakeLayer_1(
          this,
          Invocation.method(
            #addNewLayer,
            [],
            {#type: type},
          ),
        ),
        returnValueForMissingStub: _FakeLayer_1(
          this,
          Invocation.method(
            #addNewLayer,
            [],
            {#type: type},
          ),
        ),
      ) as _i3.Layer);

  @override
  void deleteLayers(List<_i3.Layer>? selectedLayers) => super.noSuchMethod(
        Invocation.method(
          #deleteLayers,
          [selectedLayers],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void renameLayer(
    _i3.Layer? layer,
    String? newName,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #renameLayer,
          [
            layer,
            newName,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void syncLayerIndexes() => super.noSuchMethod(
        Invocation.method(
          #syncLayerIndexes,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Node? canvasItemNodeFromLayer(_i3.Layer? layer) => (super.noSuchMethod(
        Invocation.method(
          #canvasItemNodeFromLayer,
          [layer],
        ),
        returnValueForMissingStub: null,
      ) as _i4.Node?);

  @override
  _i3.Layer? getLayerFromPosition(
    _i5.Offset? position,
    List<_i14.CanvasItem>? items,
    List<_i3.Layer>? layers,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLayerFromPosition,
          [
            position,
            items,
            layers,
          ],
        ),
        returnValueForMissingStub: null,
      ) as _i3.Layer?);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) => super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [NodegraphsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNodegraphsService extends _i1.Mock implements _i15.NodegraphsService {
  @override
  Map<String, _i4.Node> get nodes => (super.noSuchMethod(
        Invocation.getter(#nodes),
        returnValue: <String, _i4.Node>{},
        returnValueForMissingStub: <String, _i4.Node>{},
      ) as Map<String, _i4.Node>);

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  void selectNode(_i4.Node? node) => super.noSuchMethod(
        Invocation.method(
          #selectNode,
          [node],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void moveNode(
    _i4.Node? node,
    _i5.Offset? newPosition,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #moveNode,
          [
            node,
            newPosition,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEditNodePropertyValue(
    _i16.Property<dynamic>? property,
    dynamic value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onEditNodePropertyValue,
          [
            property,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onSetPropertyExposed(
    _i16.Property<dynamic>? property,
    bool? isExposed,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onSetPropertyExposed,
          [
            property,
            isExposed,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) => super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [IdService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIdService extends _i1.Mock implements _i17.IdService {
  @override
  String newId() => (super.noSuchMethod(
        Invocation.method(
          #newId,
          [],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #newId,
            [],
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #newId,
            [],
          ),
        ),
      ) as String);
}

/// A class which mocks [NodeRegistryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNodeRegistryService extends _i1.Mock implements _i18.NodeRegistryService {
  @override
  Map<String, _i4.Node> get nodeRegistry => (super.noSuchMethod(
        Invocation.getter(#nodeRegistry),
        returnValue: <String, _i4.Node>{},
        returnValueForMissingStub: <String, _i4.Node>{},
      ) as Map<String, _i4.Node>);

  @override
  void registerNodeType(_i4.Node? node) => super.noSuchMethod(
        Invocation.method(
          #registerNodeType,
          [node],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Node createNode(
    String? idname,
    _i5.Offset? position,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNode,
          [
            idname,
            position,
          ],
        ),
        returnValue: _FakeNode_2(
          this,
          Invocation.method(
            #createNode,
            [
              idname,
              position,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeNode_2(
          this,
          Invocation.method(
            #createNode,
            [
              idname,
              position,
            ],
          ),
        ),
      ) as _i4.Node);
}

/// A class which mocks [DocumentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentService extends _i1.Mock implements _i19.DocumentService {
  @override
  int get selectedDocumentIndex => (super.noSuchMethod(
        Invocation.getter(#selectedDocumentIndex),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  List<_i20.Document> get documents => (super.noSuchMethod(
        Invocation.getter(#documents),
        returnValue: <_i20.Document>[],
        returnValueForMissingStub: <_i20.Document>[],
      ) as List<_i20.Document>);

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  void setSelectedDocumentTab(_i20.Document? selectedDocument) => super.noSuchMethod(
        Invocation.method(
          #setSelectedDocumentTab,
          [selectedDocument],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reorderDocumentTabs(
    int? oldIndex,
    int? newIndex,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #reorderDocumentTabs,
          [
            oldIndex,
            newIndex,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void createNewDocument(
    String? name,
    _i5.Size? size,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #createNewDocument,
          [
            name,
            size,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void openExistingDocument() => super.noSuchMethod(
        Invocation.method(
          #openExistingDocument,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void closeDocument(_i20.Document? document) => super.noSuchMethod(
        Invocation.method(
          #closeDocument,
          [document],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> saveDocument(_i20.Document? document) => (super.noSuchMethod(
        Invocation.method(
          #saveDocument,
          [document],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> saveDocumentToFile(_i20.Document? document) => (super.noSuchMethod(
        Invocation.method(
          #saveDocumentToFile,
          [document],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void renameDocument(
    _i20.Document? document,
    String? newName,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #renameDocument,
          [
            document,
            newName,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setEvaluationResult(List<_i14.CanvasItem>? result) => super.noSuchMethod(
        Invocation.method(
          #setEvaluationResult,
          [result],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) => super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [EvaluationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEvaluationService extends _i1.Mock implements _i21.EvaluationService {
  @override
  List<_i3.Layer> get layers => (super.noSuchMethod(
        Invocation.getter(#layers),
        returnValue: <_i3.Layer>[],
        returnValueForMissingStub: <_i3.Layer>[],
      ) as List<_i3.Layer>);

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  void evaluate({List<_i3.Layer>? evaluateLayers = const []}) => super.noSuchMethod(
        Invocation.method(
          #evaluate,
          [],
          {#evaluateLayers: evaluateLayers},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) => super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ExportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExportService extends _i1.Mock implements _i22.ExportService {
  @override
  _i9.Future<bool> export(
    List<_i14.CanvasItem>? canvasItems,
    _i5.Size? canvasSize,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #export,
          [
            canvasItems,
            canvasSize,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> exportToImageFormat(
    String? exportPath,
    _i23.ExportImageFormat? exportFormat,
    List<_i14.CanvasItem>? canvasItems,
    _i5.Size? canvasSize,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportToImageFormat,
          [
            exportPath,
            exportFormat,
            canvasItems,
            canvasSize,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i23.ExportImageFormat? extensionToExportImageFormat(String? imageExtension) => (super.noSuchMethod(
        Invocation.method(
          #extensionToExportImageFormat,
          [imageExtension],
        ),
        returnValueForMissingStub: null,
      ) as _i23.ExportImageFormat?);

  @override
  _i9.Future<_i5.Image> getUiImageFromCanvas(
    List<_i14.CanvasItem>? canvasItems,
    _i5.Size? canvasSize,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUiImageFromCanvas,
          [
            canvasItems,
            canvasSize,
          ],
        ),
        returnValue: _i9.Future<_i5.Image>.value(_FakeImage_3(
          this,
          Invocation.method(
            #getUiImageFromCanvas,
            [
              canvasItems,
              canvasSize,
            ],
          ),
        )),
        returnValueForMissingStub: _i9.Future<_i5.Image>.value(_FakeImage_3(
          this,
          Invocation.method(
            #getUiImageFromCanvas,
            [
              canvasItems,
              canvasSize,
            ],
          ),
        )),
      ) as _i9.Future<_i5.Image>);

  @override
  _i9.Future<_i24.Image?> convertUiImageToImage(_i5.Image? uiImage) => (super.noSuchMethod(
        Invocation.method(
          #convertUiImageToImage,
          [uiImage],
        ),
        returnValue: _i9.Future<_i24.Image?>.value(),
        returnValueForMissingStub: _i9.Future<_i24.Image?>.value(),
      ) as _i9.Future<_i24.Image?>);
}

/// A class which mocks [CursorToolService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCursorToolService extends _i1.Mock implements _i25.CursorToolService {
  @override
  Map<String, _i5.Offset> get draggingStartPositions => (super.noSuchMethod(
        Invocation.getter(#draggingStartPositions),
        returnValue: <String, _i5.Offset>{},
        returnValueForMissingStub: <String, _i5.Offset>{},
      ) as Map<String, _i5.Offset>);

  @override
  set draggingStartPositions(Map<String, _i5.Offset>? _draggingStartPositions) => super.noSuchMethod(
        Invocation.setter(
          #draggingStartPositions,
          _draggingStartPositions,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set lastPosition(_i5.Offset? _lastPosition) => super.noSuchMethod(
        Invocation.setter(
          #lastPosition,
          _lastPosition,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i3.Layer> get layers => (super.noSuchMethod(
        Invocation.getter(#layers),
        returnValue: <_i3.Layer>[],
        returnValueForMissingStub: <_i3.Layer>[],
      ) as List<_i3.Layer>);

  @override
  List<_i3.Layer> get selectedLayers => (super.noSuchMethod(
        Invocation.getter(#selectedLayers),
        returnValue: <_i3.Layer>[],
        returnValueForMissingStub: <_i3.Layer>[],
      ) as List<_i3.Layer>);

  @override
  List<_i14.CanvasItem> get items => (super.noSuchMethod(
        Invocation.getter(#items),
        returnValue: <_i14.CanvasItem>[],
        returnValueForMissingStub: <_i14.CanvasItem>[],
      ) as List<_i14.CanvasItem>);

  @override
  void activate() => super.noSuchMethod(
        Invocation.method(
          #activate,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deactivate() => super.noSuchMethod(
        Invocation.method(
          #deactivate,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onHover(_i26.PointerHoverEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onHover,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTapDown(_i6.TapDownDetails? event) => super.noSuchMethod(
        Invocation.method(
          #onTapDown,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPanDown(_i6.DragDownDetails? event) => super.noSuchMethod(
        Invocation.method(
          #onPanDown,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPanUpdate(_i6.DragUpdateDetails? event) => super.noSuchMethod(
        Invocation.method(
          #onPanUpdate,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPanCancel() => super.noSuchMethod(
        Invocation.method(
          #onPanCancel,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPanEnd(_i6.DragEndDetails? event) => super.noSuchMethod(
        Invocation.method(
          #onPanEnd,
          [event],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RectangleToolService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRectangleToolService extends _i1.Mock implements _i27.RectangleToolService {
  @override
  set draggingStartPosition(_i5.Offset? _draggingStartPosition) => super.noSuchMethod(
        Invocation.setter(
          #draggingStartPosition,
          _draggingStartPosition,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set lastPosition(_i5.Offset? _lastPosition) => super.noSuchMethod(
        Invocation.setter(
          #lastPosition,
          _lastPosition,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i3.Layer> get layers => (super.noSuchMethod(
        Invocation.getter(#layers),
        returnValue: <_i3.Layer>[],
        returnValueForMissingStub: <_i3.Layer>[],
      ) as List<_i3.Layer>);

  @override
  List<_i3.Layer> get selectedLayers => (super.noSuchMethod(
        Invocation.getter(#selectedLayers),
        returnValue: <_i3.Layer>[],
        returnValueForMissingStub: <_i3.Layer>[],
      ) as List<_i3.Layer>);

  @override
  List<_i14.CanvasItem> get items => (super.noSuchMethod(
        Invocation.getter(#items),
        returnValue: <_i14.CanvasItem>[],
        returnValueForMissingStub: <_i14.CanvasItem>[],
      ) as List<_i14.CanvasItem>);

  @override
  void activate() => super.noSuchMethod(
        Invocation.method(
          #activate,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deactivate() => super.noSuchMethod(
        Invocation.method(
          #deactivate,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onHover(_i26.PointerHoverEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onHover,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTapDown(_i6.TapDownDetails? event) => super.noSuchMethod(
        Invocation.method(
          #onTapDown,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPanDown(_i6.DragDownDetails? event) => super.noSuchMethod(
        Invocation.method(
          #onPanDown,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPanUpdate(_i6.DragUpdateDetails? event) => super.noSuchMethod(
        Invocation.method(
          #onPanUpdate,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPanCancel() => super.noSuchMethod(
        Invocation.method(
          #onPanCancel,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPanEnd(_i6.DragEndDetails? event) => super.noSuchMethod(
        Invocation.method(
          #onPanEnd,
          [event],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ToolService].
///
/// See the documentation for Mockito's code generation for more information.
class MockToolService extends _i1.Mock implements _i28.ToolService {
  @override
  _i2.Tool get activeTool => (super.noSuchMethod(
        Invocation.getter(#activeTool),
        returnValue: _i2.Tool.cursor,
        returnValueForMissingStub: _i2.Tool.cursor,
      ) as _i2.Tool);

  @override
  _i2.ToolModeEventHandler get toolModeHandler => (super.noSuchMethod(
        Invocation.getter(#toolModeHandler),
        returnValue: _FakeToolModeEventHandler_0(
          this,
          Invocation.getter(#toolModeHandler),
        ),
        returnValueForMissingStub: _FakeToolModeEventHandler_0(
          this,
          Invocation.getter(#toolModeHandler),
        ),
      ) as _i2.ToolModeEventHandler);

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  void setActiveTool(_i2.Tool? tool) => super.noSuchMethod(
        Invocation.method(
          #setActiveTool,
          [tool],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setToolEventHandler(_i2.Tool? tool) => super.noSuchMethod(
        Invocation.method(
          #setToolEventHandler,
          [tool],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ToolModeEventHandler getToolModeHandler(_i2.Tool? activeTool) => (super.noSuchMethod(
        Invocation.method(
          #getToolModeHandler,
          [activeTool],
        ),
        returnValue: _FakeToolModeEventHandler_0(
          this,
          Invocation.method(
            #getToolModeHandler,
            [activeTool],
          ),
        ),
        returnValueForMissingStub: _FakeToolModeEventHandler_0(
          this,
          Invocation.method(
            #getToolModeHandler,
            [activeTool],
          ),
        ),
      ) as _i2.ToolModeEventHandler);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) => super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [OverlaysService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOverlaysService extends _i1.Mock implements _i29.OverlaysService {
  @override
  String get textInputOverlayText => (super.noSuchMethod(
        Invocation.getter(#textInputOverlayText),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#textInputOverlayText),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#textInputOverlayText),
        ),
      ) as String);

  @override
  set textInputOverlayText(String? _textInputOverlayText) => super.noSuchMethod(
        Invocation.setter(
          #textInputOverlayText,
          _textInputOverlayText,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i3.Layer> get selectedLayers => (super.noSuchMethod(
        Invocation.getter(#selectedLayers),
        returnValue: <_i3.Layer>[],
        returnValueForMissingStub: <_i3.Layer>[],
      ) as List<_i3.Layer>);

  @override
  bool get showOverlays => (super.noSuchMethod(
        Invocation.getter(#showOverlays),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  double get viewportScale => (super.noSuchMethod(
        Invocation.getter(#viewportScale),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  void setViewportScale(double? scale) => super.noSuchMethod(
        Invocation.method(
          #setViewportScale,
          [scale],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void changeText(String? text) => super.noSuchMethod(
        Invocation.method(
          #changeText,
          [text],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isWithinSelectionBounds(_i5.Offset? position) => (super.noSuchMethod(
        Invocation.method(
          #isWithinSelectionBounds,
          [position],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i30.SelectionBoxOverlay? calculateSelectionBoxOverlay(
    List<_i3.Layer>? selectedLayers,
    double? viewportScale,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateSelectionBoxOverlay,
          [
            selectedLayers,
            viewportScale,
          ],
        ),
        returnValueForMissingStub: null,
      ) as _i30.SelectionBoxOverlay?);

  @override
  _i5.Rect calculateMinBounds(List<_i3.Layer>? selectedLayers) => (super.noSuchMethod(
        Invocation.method(
          #calculateMinBounds,
          [selectedLayers],
        ),
        returnValue: _FakeRect_4(
          this,
          Invocation.method(
            #calculateMinBounds,
            [selectedLayers],
          ),
        ),
        returnValueForMissingStub: _FakeRect_4(
          this,
          Invocation.method(
            #calculateMinBounds,
            [selectedLayers],
          ),
        ),
      ) as _i5.Rect);

  @override
  void setShowOverlays(bool? showOverlays) => super.noSuchMethod(
        Invocation.method(
          #setShowOverlays,
          [showOverlays],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) => super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [HandToolService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHandToolService extends _i1.Mock implements _i31.HandToolService {
  @override
  void activate() => super.noSuchMethod(
        Invocation.method(
          #activate,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deactivate() => super.noSuchMethod(
        Invocation.method(
          #deactivate,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onHover(_i26.PointerHoverEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onHover,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTapDown(_i6.TapDownDetails? event) => super.noSuchMethod(
        Invocation.method(
          #onTapDown,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPanDown(_i6.DragDownDetails? event) => super.noSuchMethod(
        Invocation.method(
          #onPanDown,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPanUpdate(_i6.DragUpdateDetails? event) => super.noSuchMethod(
        Invocation.method(
          #onPanUpdate,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPanCancel() => super.noSuchMethod(
        Invocation.method(
          #onPanCancel,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPanEnd(_i6.DragEndDetails? event) => super.noSuchMethod(
        Invocation.method(
          #onPanEnd,
          [event],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CanvasService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCanvasService extends _i1.Mock implements _i32.CanvasService {
  @override
  _i6.MouseCursor get mouseCursor => (super.noSuchMethod(
        Invocation.getter(#mouseCursor),
        returnValue: _FakeMouseCursor_5(
          this,
          Invocation.getter(#mouseCursor),
        ),
        returnValueForMissingStub: _FakeMouseCursor_5(
          this,
          Invocation.getter(#mouseCursor),
        ),
      ) as _i6.MouseCursor);

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  void setMouseCursor(_i6.MouseCursor? cursor) => super.noSuchMethod(
        Invocation.method(
          #setMouseCursor,
          [cursor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) => super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ImageToolService].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageToolService extends _i1.Mock implements _i33.ImageToolService {
  @override
  set draggingStartPosition(_i5.Offset? _draggingStartPosition) => super.noSuchMethod(
        Invocation.setter(
          #draggingStartPosition,
          _draggingStartPosition,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set lastPosition(_i5.Offset? _lastPosition) => super.noSuchMethod(
        Invocation.setter(
          #lastPosition,
          _lastPosition,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set photo(_i34.Photo? _photo) => super.noSuchMethod(
        Invocation.setter(
          #photo,
          _photo,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get photoWidth => (super.noSuchMethod(
        Invocation.getter(#photoWidth),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  set photoWidth(int? _photoWidth) => super.noSuchMethod(
        Invocation.setter(
          #photoWidth,
          _photoWidth,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get photoHeight => (super.noSuchMethod(
        Invocation.getter(#photoHeight),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  set photoHeight(int? _photoHeight) => super.noSuchMethod(
        Invocation.setter(
          #photoHeight,
          _photoHeight,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get lockAspectRatio => (super.noSuchMethod(
        Invocation.getter(#lockAspectRatio),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set lockAspectRatio(bool? _lockAspectRatio) => super.noSuchMethod(
        Invocation.setter(
          #lockAspectRatio,
          _lockAspectRatio,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i3.Layer> get layers => (super.noSuchMethod(
        Invocation.getter(#layers),
        returnValue: <_i3.Layer>[],
        returnValueForMissingStub: <_i3.Layer>[],
      ) as List<_i3.Layer>);

  @override
  List<_i3.Layer> get selectedLayers => (super.noSuchMethod(
        Invocation.getter(#selectedLayers),
        returnValue: <_i3.Layer>[],
        returnValueForMissingStub: <_i3.Layer>[],
      ) as List<_i3.Layer>);

  @override
  List<_i14.CanvasItem> get items => (super.noSuchMethod(
        Invocation.getter(#items),
        returnValue: <_i14.CanvasItem>[],
        returnValueForMissingStub: <_i14.CanvasItem>[],
      ) as List<_i14.CanvasItem>);

  @override
  void activate() => super.noSuchMethod(
        Invocation.method(
          #activate,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deactivate() => super.noSuchMethod(
        Invocation.method(
          #deactivate,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onHover(_i26.PointerHoverEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onHover,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTapDown(_i6.TapDownDetails? event) => super.noSuchMethod(
        Invocation.method(
          #onTapDown,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPanDown(_i6.DragDownDetails? event) => super.noSuchMethod(
        Invocation.method(
          #onPanDown,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPanUpdate(_i6.DragUpdateDetails? event) => super.noSuchMethod(
        Invocation.method(
          #onPanUpdate,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPanCancel() => super.noSuchMethod(
        Invocation.method(
          #onPanCancel,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPanEnd(_i6.DragEndDetails? event) => super.noSuchMethod(
        Invocation.method(
          #onPanEnd,
          [event],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TextToolService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTextToolService extends _i1.Mock implements _i35.TextToolService {
  @override
  set draggingStartPosition(_i5.Offset? _draggingStartPosition) => super.noSuchMethod(
        Invocation.setter(
          #draggingStartPosition,
          _draggingStartPosition,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set lastPosition(_i5.Offset? _lastPosition) => super.noSuchMethod(
        Invocation.setter(
          #lastPosition,
          _lastPosition,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i3.Layer> get layers => (super.noSuchMethod(
        Invocation.getter(#layers),
        returnValue: <_i3.Layer>[],
        returnValueForMissingStub: <_i3.Layer>[],
      ) as List<_i3.Layer>);

  @override
  List<_i3.Layer> get selectedLayers => (super.noSuchMethod(
        Invocation.getter(#selectedLayers),
        returnValue: <_i3.Layer>[],
        returnValueForMissingStub: <_i3.Layer>[],
      ) as List<_i3.Layer>);

  @override
  List<_i14.CanvasItem> get items => (super.noSuchMethod(
        Invocation.getter(#items),
        returnValue: <_i14.CanvasItem>[],
        returnValueForMissingStub: <_i14.CanvasItem>[],
      ) as List<_i14.CanvasItem>);

  @override
  void activate() => super.noSuchMethod(
        Invocation.method(
          #activate,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deactivate() => super.noSuchMethod(
        Invocation.method(
          #deactivate,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onHover(_i26.PointerHoverEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onHover,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTapDown(_i6.TapDownDetails? event) => super.noSuchMethod(
        Invocation.method(
          #onTapDown,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPanDown(_i6.DragDownDetails? event) => super.noSuchMethod(
        Invocation.method(
          #onPanDown,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPanUpdate(_i6.DragUpdateDetails? event) => super.noSuchMethod(
        Invocation.method(
          #onPanUpdate,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPanCancel() => super.noSuchMethod(
        Invocation.method(
          #onPanCancel,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPanEnd(_i6.DragEndDetails? event) => super.noSuchMethod(
        Invocation.method(
          #onPanEnd,
          [event],
        ),
        returnValueForMissingStub: null,
      );
}
