import json
import requests

digits_mapping = {
    "1": "One",
    "2": "Two",
    "3": "Three",
    "4": "Four",
    "5": "Five",
    "6": "Six",
    "7": "Seven",
    "8": "Eight",
    "9": "Nine"
}

TOP_OF_FILE = """/***********************************************************************************
** Warning! This file was auto-generated by "GimelStudio/tools/generateiconcodes.py"
** Any changes made to this file will be LOST
***********************************************************************************/

#ifndef GS_UI_ICONCODES_H
#define GS_UI_ICONCODES_H

#include <QObject>

namespace gs::ui {

class IconCode
{
    Q_GADGET

public:
    enum class Code : char16_t {
        None = 0xFFFF,\n"""

BOTTOM_OF_FILE = """    };

    Q_ENUM(Code)
};
}

#endif // GS_UI_ICONCODES_H\n"""

r = requests.get("https://raw.githubusercontent.com/twbs/icons/main/font/bootstrap-icons.json")
icons_dict = r.json()

# Clear the file
open("../src/framework/ui/iconcodes.h", "w+").close()

# Write to the file
with open("../src/framework/ui/iconcodes.h", "a") as f:
    f.write(TOP_OF_FILE)

    for icon_name, icon_code in icons_dict.items():
        # TODO: Should probably replace all the digits for consistency
        if (icon_name[0].isdigit()):
            icon_name = icon_name[0].replace(icon_name[0], digits_mapping[icon_name[0]]) + icon_name[1:]

        f.write(f"        {icon_name.title().replace('-', '')} = {str(hex(icon_code)).upper()},\n")

    f.write(BOTTOM_OF_FILE)
