on:
  push:
    branches:
      - master

name: Gimel Studio CI Build
jobs:

  linux:
    name: Linux (Debian) build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake libgtk-3-dev ninja-build

      - name: Set up Flutter and build application
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.0
      - run: |
          flutter pub get
          flutter build linux --release

      - name: Create tar.gz archive
        run: |
          cd build/linux/x64/release/bundle
          tar -czvf ../../../../../GimelStudio.tar.gz *

      - name: Upload tar.gz archive
        uses: actions/upload-artifact@v4
        with:
          name: Linux (Debian) binary
          path: ./*.tar.gz


  windows:
    name: Windows build
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Set up Flutter and build application
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.0
      - run: |
          flutter pub get
          flutter build windows --release

      - name: Build Windows Installer
        run: dart run msix:create

      - name: Upload MSIX
        uses: actions/upload-artifact@v4
        with:
          path: build\windows\x64\runner\Release\GimelStudio.msix


  macos:
    name: macOs build
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Set up Flutter and build application
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.0
      - run: |
          flutter pub get
          flutter build macos --release

      - name: Zip application files
        run: |
          cd build/macos/Build/Products/Release
          zip -yr GimelStudio.zip Gimelstudio.app

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          path: build/macos/Build/Products/Release/GimelStudio.zip
    