on:
  push:
    branches:
      - master

name: Gimel Studio CI Build
jobs:

  linux:
    name: Linux (Debian) build
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Install Flutter dependencies
        run: |
          sudo apt-get update -y && sudo apt-get upgrade -y;
          sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa
          sudo apt-get install clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.0

      - name: Check Flutter install
        run: flutter doctor -v

      - name: Build application
        run: |
          flutter pub get
          flutter build linux --release

      - name: Create tar.gz archive
        run: |
          cd build/linux/x64/release/bundle
          tar -czvf ../../../../../GimelStudio.tar.gz *

      - name: Upload tar.gz archive
        uses: actions/upload-artifact@v4
        with:
          name: GimelStudio-Linux
          path: ./*.tar.gz


  windows:
    name: Windows build
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Set up Flutter and build application
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.0
      - run: |
          flutter pub get
          flutter build windows --release

      - name: Zip application files
        run: |
          cd build\windows\x64\runner\Release\
          powershell Compress-Archive .\* GimelStudio.zip

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: GimelStudio-Windows
          path: build\windows\x64\runner\Release\GimelStudio.zip


  macos:
    name: macOs build
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Set up Flutter and build application
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.0
      - run: |
          flutter pub get
          flutter build macos --release

      - name: Zip application files
        run: |
          cd build/macos/Build/Products/Release
          zip -r GimelStudio.zip .

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: GimelStudio-macOs
          path: build/macos/Build/Products/Release/GimelStudio.zip
    
