on:
  push:
    branches:
      - master

name: app.gimelstudio.com
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Set up Flutter and build web application
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.29.0
    - run: flutter pub get
    - run: flutter build web --dart-define=PLATFORM=Web --dart-define=BUILD_DATETIME=${{ github.event.repository.updated_at}} --dart-define=BUILD_BRANCH=${{ github.head_ref || github.ref_name }} --dart-define=BUILD_COMMIT=${{ github.sha }}
    
    - name: Push build files to branch
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: webapp-build
        FOLDER: build/web
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE: "Build ({sha}) {msg}"